//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Tools.ModManager {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModManager_I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModManager_I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Tools.ModManager.ModManager_I18n", typeof(ModManager_I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加右键菜单 的本地化字符串。
        /// </summary>
        public static string AddContextMenu {
            get {
                return ResourceManager.GetString("AddContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加菜单项 的本地化字符串。
        /// </summary>
        public static string AddMenuItem {
            get {
                return ResourceManager.GetString("AddMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加模组 的本地化字符串。
        /// </summary>
        public static string AddMod {
            get {
                return ResourceManager.GetString("AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加模组至用户分组 的本地化字符串。
        /// </summary>
        public static string AddModToUserGroup {
            get {
                return ResourceManager.GetString("AddModToUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加用户分组 的本地化字符串。
        /// </summary>
        public static string AddUserGroup {
            get {
                return ResourceManager.GetString("AddUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命名失败,名字为空或者已存在相同名字的分组 的本地化字符串。
        /// </summary>
        public static string AddUserNamingFailed {
            get {
                return ResourceManager.GetString("AddUserNamingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部模组 的本地化字符串。
        /// </summary>
        public static string AllMods {
            get {
                return ResourceManager.GetString("AllMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同名称的用户分组 的本地化字符串。
        /// </summary>
        public static string AlreadyExistUserGroup {
            get {
                return ResourceManager.GetString("AlreadyExistUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 美化模组 的本地化字符串。
        /// </summary>
        public static string BeautifyMods {
            get {
                return ResourceManager.GetString("BeautifyMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消收藏所选模组 的本地化字符串。
        /// </summary>
        public static string CancelCollectionSelectedMods {
            get {
                return ResourceManager.GetString("CancelCollectionSelectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组 {0} 在用户分组 {1} 的状态修改为 {2} 的本地化字符串。
        /// </summary>
        public static string ChangeModUserGroup {
            get {
                return ResourceManager.GetString("ChangeModUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类至 的本地化字符串。
        /// </summary>
        public static string ClassifyTo {
            get {
                return ResourceManager.GetString("ClassifyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭详情 的本地化字符串。
        /// </summary>
        public static string CloseDetails {
            get {
                return ResourceManager.GetString("CloseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已收藏 的本地化字符串。
        /// </summary>
        public static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已收藏模组 的本地化字符串。
        /// </summary>
        public static string CollectedMods {
            get {
                return ResourceManager.GetString("CollectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏所选模组 的本地化字符串。
        /// </summary>
        public static string CollectionSelectedMods {
            get {
                return ResourceManager.GetString("CollectionSelectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除模组 的本地化字符串。
        /// </summary>
        public static string ConfirmDeleteMod {
            get {
                return ResourceManager.GetString("ConfirmDeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认倒拖入文件 的本地化字符串。
        /// </summary>
        public static string ConfirmDragFiles {
            get {
                return ResourceManager.GetString("ConfirmDragFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容拓展 的本地化字符串。
        /// </summary>
        public static string ContentExpansions {
            get {
                return ResourceManager.GetString("ContentExpansions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右键菜单刷新完成 的本地化字符串。
        /// </summary>
        public static string ContextMenuRefreshComplete {
            get {
                return ResourceManager.GetString("ContextMenuRefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制信息 的本地化字符串。
        /// </summary>
        public static string CopyInfo {
            get {
                return ResourceManager.GetString("CopyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建文件 的本地化字符串。
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除模组 的本地化字符串。
        /// </summary>
        public static string DeleteMod {
            get {
                return ResourceManager.GetString("DeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖模组 的本地化字符串。
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用所有已启用模组 的本地化字符串。
        /// </summary>
        public static string DisableAllEnabledMods {
            get {
                return ResourceManager.GetString("DisableAllEnabledMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用的模组 的本地化字符串。
        /// </summary>
        public static string DisabledMod {
            get {
                return ResourceManager.GetString("DisabledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用所选模组 的本地化字符串。
        /// </summary>
        public static string DisableSelectedMods {
            get {
                return ResourceManager.GetString("DisableSelectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用前置 的本地化字符串。
        /// </summary>
        public static string EnableDependencies {
            get {
                return ResourceManager.GetString("EnableDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用的模组 的本地化字符串。
        /// </summary>
        public static string EnabledMod {
            get {
                return ResourceManager.GetString("EnabledMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用模组文件 的本地化字符串。
        /// </summary>
        public static string EnabledModsFile {
            get {
                return ResourceManager.GetString("EnabledModsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用所选模组 的本地化字符串。
        /// </summary>
        public static string EnabledSelectedMods {
            get {
                return ResourceManager.GetString("EnabledSelectedMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        public static string EnabledStatus {
            get {
                return ResourceManager.GetString("EnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用模组 的本地化字符串。
        /// </summary>
        public static string EnableMod {
            get {
                return ResourceManager.GetString("EnableMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出至文件 的本地化字符串。
        /// </summary>
        public static string ExportEnabledModsListToFile {
            get {
                return ResourceManager.GetString("ExportEnabledModsListToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出用户数据 的本地化字符串。
        /// </summary>
        public static string ExportUserData {
            get {
                return ResourceManager.GetString("ExportUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出用户分组 的本地化字符串。
        /// </summary>
        public static string ExportUserGroup {
            get {
                return ResourceManager.GetString("ExportUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 派系模组 的本地化字符串。
        /// </summary>
        public static string FactionMods {
            get {
                return ResourceManager.GetString("FactionMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件错误 的本地化字符串。
        /// </summary>
        public static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        public static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹不存在 的本地化字符串。
        /// </summary>
        public static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组类型分组 的本地化字符串。
        /// </summary>
        public static string GroupedByModType {
            get {
                return ResourceManager.GetString("GroupedByModType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组数量刷新完成 的本地化字符串。
        /// </summary>
        public static string GroupModCountRefresh {
            get {
                return ResourceManager.GetString("GroupModCountRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组显示数量刷新完成 的本地化字符串。
        /// </summary>
        public static string GroupModCountRefreshComplete {
            get {
                return ResourceManager.GetString("GroupModCountRefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件导入 的本地化字符串。
        /// </summary>
        public static string ImportEnabledModsListFromFile {
            get {
                return ResourceManager.GetString("ImportEnabledModsListFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从游戏存档导入 的本地化字符串。
        /// </summary>
        public static string ImportEnabledModsListFromSave {
            get {
                return ResourceManager.GetString("ImportEnabledModsListFromSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入用户数据 的本地化字符串。
        /// </summary>
        public static string ImportUserData {
            get {
                return ResourceManager.GetString("ImportUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入用户分组 的本地化字符串。
        /// </summary>
        public static string ImportUserGroup {
            get {
                return ResourceManager.GetString("ImportUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化完成 的本地化字符串。
        /// </summary>
        public static string InitialisationComplete {
            get {
                return ResourceManager.GetString("InitialisationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是功能性模组
        ///可以中途移除 的本地化字符串。
        /// </summary>
        public static string IsUtilityMod {
            get {
                return ResourceManager.GetString("IsUtilityMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前置模组 的本地化字符串。
        /// </summary>
        public static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载收藏列表 的本地化字符串。
        /// </summary>
        public static string LoadCollectedList {
            get {
                return ResourceManager.GetString("LoadCollectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载已启用模组文件 的本地化字符串。
        /// </summary>
        public static string LoadEnabledModsFile {
            get {
                return ResourceManager.GetString("LoadEnabledModsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载用户自定义数据 的本地化字符串。
        /// </summary>
        public static string LoadUserCustomData {
            get {
                return ResourceManager.GetString("LoadUserCustomData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载用户数据 的本地化字符串。
        /// </summary>
        public static string LoadUserData {
            get {
                return ResourceManager.GetString("LoadUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载用户分组 的本地化字符串。
        /// </summary>
        public static string LoadUserGroup {
            get {
                return ResourceManager.GetString("LoadUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作启用列表 的本地化字符串。
        /// </summary>
        public static string ManipulateEnabledList {
            get {
                return ResourceManager.GetString("ManipulateEnabledList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作用户数据 的本地化字符串。
        /// </summary>
        public static string ManipulateUserData {
            get {
                return ResourceManager.GetString("ManipulateUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含收藏列表和用户描述 的本地化字符串。
        /// </summary>
        public static string ManipulateUserDataToolTip {
            get {
                return ResourceManager.GetString("ManipulateUserDataToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作用户分组 的本地化字符串。
        /// </summary>
        public static string ManipulateUserGroup {
            get {
                return ResourceManager.GetString("ManipulateUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大随机数量 的本地化字符串。
        /// </summary>
        public static string MaxRandomNumber {
            get {
                return ResourceManager.GetString("MaxRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大型模组 的本地化字符串。
        /// </summary>
        public static string MegaMods {
            get {
                return ResourceManager.GetString("MegaMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小随机数量 的本地化字符串。
        /// </summary>
        public static string MinRandomNumber {
            get {
                return ResourceManager.GetString("MinRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小随机数不能大于最大随机数 的本地化字符串。
        /// </summary>
        public static string MinRandomNumberCannotGreaterMaxRandomNumber {
            get {
                return ResourceManager.GetString("MinRandomNumberCannotGreaterMaxRandomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 闲杂模组 的本地化字符串。
        /// </summary>
        public static string MiscellaneousMods {
            get {
                return ResourceManager.GetString("MiscellaneousMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组添加失败 的本地化字符串。
        /// </summary>
        public static string ModAddFailed {
            get {
                return ResourceManager.GetString("ModAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组添加 成功数量: {0} 失败数量: {1} 的本地化字符串。
        /// </summary>
        public static string ModAddSize {
            get {
                return ResourceManager.GetString("ModAddSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组添加成功 的本地化字符串。
        /// </summary>
        public static string ModAddSuccess {
            get {
                return ResourceManager.GetString("ModAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收藏状态修改为 的本地化字符串。
        /// </summary>
        public static string ModCollectedStatus {
            get {
                return ResourceManager.GetString("ModCollectedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态修改为 的本地化字符串。
        /// </summary>
        public static string ModEnabledStatus {
            get {
                return ResourceManager.GetString("ModEnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组分组获取失败 的本地化字符串。
        /// </summary>
        public static string ModGroupFailedToGet {
            get {
                return ResourceManager.GetString("ModGroupFailedToGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组信息 的本地化字符串。
        /// </summary>
        public static string ModInfo {
            get {
                return ResourceManager.GetString("ModInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组管理器 的本地化字符串。
        /// </summary>
        public static string ModManager {
            get {
                return ResourceManager.GetString("ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组显示信息设置成功 的本地化字符串。
        /// </summary>
        public static string ModShowInfoSetSuccess {
            get {
                return ResourceManager.GetString("ModShowInfoSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未收藏 的本地化字符串。
        /// </summary>
        public static string NotCollected {
            get {
                return ResourceManager.GetString("NotCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用前置 的本地化字符串。
        /// </summary>
        public static string NotEnableDependencies {
            get {
                return ResourceManager.GetString("NotEnableDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未在游戏的模组文件夹中找到前置模组 的本地化字符串。
        /// </summary>
        public static string NotFoundDependencies {
            get {
                return ResourceManager.GetString("NotFoundDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到文件 的本地化字符串。
        /// </summary>
        public static string NotFoundFile {
            get {
                return ResourceManager.GetString("NotFoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未在游戏的模组文件夹中找到模组 的本地化字符串。
        /// </summary>
        public static string NotFoundMod {
            get {
                return ResourceManager.GetString("NotFoundMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是功能性模组
        ///不可以中途移除 的本地化字符串。
        /// </summary>
        public static string NotUtilityMod {
            get {
                return ResourceManager.GetString("NotUtilityMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开备份模组 的本地化字符串。
        /// </summary>
        public static string OpenBackupDirectory {
            get {
                return ResourceManager.GetString("OpenBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开目录 的本地化字符串。
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模组目录 的本地化字符串。
        /// </summary>
        public static string OpenModDirectory {
            get {
                return ResourceManager.GetString("OpenModDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开模组目录 的本地化字符串。
        /// </summary>
        public static string OpenModsDirectory {
            get {
                return ResourceManager.GetString("OpenModsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开存档目录 的本地化字符串。
        /// </summary>
        public static string OpenSaveDirectory {
            get {
                return ResourceManager.GetString("OpenSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机启用模组 的本地化字符串。
        /// </summary>
        public static string RandomEnableMods {
            get {
                return ResourceManager.GetString("RandomEnableMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大随机数不能大于用户分组所含模组总数 的本地化字符串。
        /// </summary>
        public static string RandomNumberCannotGreaterTotal {
            get {
                return ResourceManager.GetString("RandomNumberCannotGreaterTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小随机数不能小于 0 的本地化字符串。
        /// </summary>
        public static string RandomNumberCannotLess0 {
            get {
                return ResourceManager.GetString("RandomNumberCannotLess0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小随机数与最大随机数不能为空 的本地化字符串。
        /// </summary>
        public static string RandomNumberCannotNull {
            get {
                return ResourceManager.GetString("RandomNumberCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新完成 的本地化字符串。
        /// </summary>
        public static string RefreshComplete {
            get {
                return ResourceManager.GetString("RefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新列表 的本地化字符串。
        /// </summary>
        public static string RefreshList {
            get {
                return ResourceManager.GetString("RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从用户分组中删除 的本地化字符串。
        /// </summary>
        public static string RemoveFromUserGroup {
            get {
                return ResourceManager.GetString("RemoveFromUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除模组 的本地化字符串。
        /// </summary>
        public static string RemoveMod {
            get {
                return ResourceManager.GetString("RemoveMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户分组 的本地化字符串。
        /// </summary>
        public static string RemoveUserGroup {
            get {
                return ResourceManager.GetString("RemoveUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换模组 的本地化字符串。
        /// </summary>
        public static string ReplaceMod {
            get {
                return ResourceManager.GetString("ReplaceMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名用户分组 的本地化字符串。
        /// </summary>
        public static string ReplaceUserGroupName {
            get {
                return ResourceManager.GetString("ReplaceUserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在相同模组 是否覆盖?
        ///原始版本: {0}
        ///新增版本: {1} 的本地化字符串。
        /// </summary>
        public static string SameModAlreadyExists {
            get {
                return ResourceManager.GetString("SameModAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存配置 的本地化字符串。
        /// </summary>
        public static string SaveConfig {
            get {
                return ResourceManager.GetString("SaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存启用列表成功 的本地化字符串。
        /// </summary>
        public static string SaveEnabledListSuccess {
            get {
                return ResourceManager.GetString("SaveEnabledListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存用户数据成功 的本地化字符串。
        /// </summary>
        public static string SaveUserDataSuccess {
            get {
                return ResourceManager.GetString("SaveUserDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存用户分组成功 的本地化字符串。
        /// </summary>
        public static string SaveUserGroupSuccess {
            get {
                return ResourceManager.GetString("SaveUserGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索模组 的本地化字符串。
        /// </summary>
        public static string SearchMod {
            get {
                return ResourceManager.GetString("SearchMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择导入模式
        ///是:替换 否:合并 取消:取消 的本地化字符串。
        /// </summary>
        public static string SelectImportMode {
            get {
                return ResourceManager.GetString("SelectImportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示详情 的本地化字符串。
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组支持的游戏版本 的本地化字符串。
        /// </summary>
        public static string ShowGameVersion {
            get {
                return ResourceManager.GetString("ShowGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示分组 的本地化字符串。
        /// </summary>
        public static string ShowGroup {
            get {
                return ResourceManager.GetString("ShowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组作者 的本地化字符串。
        /// </summary>
        public static string ShowModAuthor {
            get {
                return ResourceManager.GetString("ShowModAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组的收藏状态 的本地化字符串。
        /// </summary>
        public static string ShowModCollectionStatus {
            get {
                return ResourceManager.GetString("ShowModCollectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组的启用状态 的本地化字符串。
        /// </summary>
        public static string ShowModEnableStatus {
            get {
                return ResourceManager.GetString("ShowModEnableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组图标 的本地化字符串。
        /// </summary>
        public static string ShowModIcon {
            get {
                return ResourceManager.GetString("ShowModIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组名称 的本地化字符串。
        /// </summary>
        public static string ShowModName {
            get {
                return ResourceManager.GetString("ShowModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示模组版本 的本地化字符串。
        /// </summary>
        public static string ShowModVersion {
            get {
                return ResourceManager.GetString("ShowModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示用户描述 的本地化字符串。
        /// </summary>
        public static string ShowUserDescription {
            get {
                return ResourceManager.GetString("ShowUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示是否为功能性模组 的本地化字符串。
        /// </summary>
        public static string ShowUtility {
            get {
                return ResourceManager.GetString("ShowUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组支持的版本与游戏版本不一致
        ///可能会出现问题 的本地化字符串。
        /// </summary>
        public static string SupportedVersionNotSameAsGameVersion {
            get {
                return ResourceManager.GetString("SupportedVersionNotSameAsGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组支持的版本与游戏版本一致 的本地化字符串。
        /// </summary>
        public static string SupportedVersionSameAsGameVersion {
            get {
                return ResourceManager.GetString("SupportedVersionSameAsGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未收藏 的本地化字符串。
        /// </summary>
        public static string UnCollected {
            get {
                return ResourceManager.GetString("UnCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未分类模组 的本地化字符串。
        /// </summary>
        public static string UnknownMods {
            get {
                return ResourceManager.GetString("UnknownMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解压错误 的本地化字符串。
        /// </summary>
        public static string UnzipError {
            get {
                return ResourceManager.GetString("UnzipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据加载错误 的本地化字符串。
        /// </summary>
        public static string UserDataLoadError {
            get {
                return ResourceManager.GetString("UserDataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户描述 的本地化字符串。
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分组 的本地化字符串。
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户分组添加成功 的本地化字符串。
        /// </summary>
        public static string UserGroupAddSuccess {
            get {
                return ResourceManager.GetString("UserGroupAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能命名为 {0} 或 {1} 的本地化字符串。
        /// </summary>
        public static string UserGroupCannotNamed {
            get {
                return ResourceManager.GetString("UserGroupCannotNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能性模组 的本地化字符串。
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能模组 的本地化字符串。
        /// </summary>
        public static string UtilityMods {
            get {
                return ResourceManager.GetString("UtilityMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件错误 的本地化字符串。
        /// </summary>
        public static string ZipFileError {
            get {
                return ResourceManager.GetString("ZipFileError", resourceCulture);
            }
        }
    }
}
