# 前置模组
"Libraries" = ["lw_lazylib", "MagicLib", "shaderLib"]
# 大型模组
"Megamods" = ["nexerelin", "IndEvo"]
# 内容模组
"ContentExpansions" = [
    "BSC",
    "HHE",
    "fluffships",
    "hte",
    "TORCHSHIPS",
    "SKR",
    "ness_saw",
    "CjyToyBox",
    "astroidships",
    "Seafood",
    "luddenhance",
    "swp",
    "ApproLightPlus",
    "SEEKER"
]
# 派系模组
"FactionMods" = [
    "LLI",
    "CFT",
    "armaa",
    "tahlan",
    "kayse_phaseships",
    "JKF",
    "mag_protect",
    "BlueSeaFisher",
    "istl_dassaultmikoyan",
    "TraverserDesignBureau",
    "valkyrian",
    "Goat_Aviation_Bureau",
    "domhist",
    "ApproLight",
    "tahlan_scalartech",
    "FantasyM",
    "XhanEmpire",
    "a111164_ExtendPack",
    "JYD",
    "gundam_uc",
    "Polaris_Prime",
    "nbj_ice",
    "KT_Association",
    "fob",
    "blackrock_driveyards",
    "ORA",
    "ArkLeg",
    "vic",
    "SCY",
    "Imperium",
    "underworld",
    "diableavionics",
    "shadow_ships",
]
# 美化模组
"BeautifyMods" = [
    "GUPPP",
    "Tartarusportraitpack",
    "Warship Girls Portrait Pack",
    "Touhou Portrait Mod",
    "intothebreachportraitpack",
    "Gia_Portrait_Pack",
]
# 功能模组
"UtilityMods" = [
    "lw_autosave",
    "DetailedCombatResults",
    "scan_those_gates",
    "ShipCatalogVariantEditor",
    "officerExtension",
    "stelnet",
    "better_deserving_smods",
    "chatter",
    "logisticsNotifications",
    "sun_ruthless_sector",
    "Torpedo_Alarm",
    "Visualized_Repair_Progress",
    "starpocalypse",
    "transpoffder",
    "sun_starship_legends",
    "System_Marker",
    "Clean_Sector",
    "advanced_gunnery_control_dbeaa06e",
    "TAR",
    "VariantAcknowledged",
]
# 闲杂模组
"MiscellaneousMods" = [
    "timid_cum",
    "timid_tmi",
    "timid_admins",
    "Terraforming & Station Construction",
    "ungp",
    "alcoholism",
    "exoticatechnologies",
    "yrex",
    "StarfarersWorkshop",
    "UGH",
    "yunrutechmining",
    "lights_out",
    "progressiveSMods",
    "timid_commissioned_hull_mods",
    "GrandColonies",
    "sun_hyperdrive",
    "wisp_NeutrinoDetectorMkII",
    "forge_production",
    "more_hullmods",
    "US",
    "efficientPop",
]
