//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Windows.MainWindow {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow_I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow_I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Windows.MainWindow.MainWindow_I18n", typeof(MainWindow_I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加菜单 的本地化字符串。
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 社区拓展 的本地化字符串。
        /// </summary>
        public static string CommunityExpansion {
            get {
                return ResourceManager.GetString("CommunityExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件错误,将恢复为默认设置 的本地化字符串。
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一次启动软件
        ///请选择游戏启动程序 的本地化字符串。
        /// </summary>
        public static string FirstStart {
            get {
                return ResourceManager.GetString("FirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 请重新选择 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SelectAgain {
            get {
                return ResourceManager.GetString("GameNotFound_SelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 软件即将退出 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SoftwareExit {
            get {
                return ResourceManager.GetString("GameNotFound_SoftwareExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常 的本地化字符串。
        /// </summary>
        public static string GlobalException {
            get {
                return ResourceManager.GetString("GlobalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常 !!!警告!!!
        ///如果你看到了这个错误,说明这是意料之外的情况
        ///可能会影响软件的正常运行,建议查看log并提交至issue. 的本地化字符串。
        /// </summary>
        public static string GlobalExceptionMessage {
            get {
                return ResourceManager.GetString("GlobalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化完成 的本地化字符串。
        /// </summary>
        public static string InitializationCompleted {
            get {
                return ResourceManager.GetString("InitializationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化错误 的本地化字符串。
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单列表刷新完成 的本地化字符串。
        /// </summary>
        public static string MenuListRefreshComplete {
            get {
                return ResourceManager.GetString("MenuListRefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组管理器 的本地化字符串。
        /// </summary>
        public static string ModManager {
            get {
                return ResourceManager.GetString("ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方拓展 的本地化字符串。
        /// </summary>
        public static string OfficialExpansion {
            get {
                return ResourceManager.GetString("OfficialExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新页面 的本地化字符串。
        /// </summary>
        public static string RefreshPage {
            get {
                return ResourceManager.GetString("RefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示页面 的本地化字符串。
        /// </summary>
        public static string ShowPage {
            get {
                return ResourceManager.GetString("ShowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远行星号工具箱 的本地化字符串。
        /// </summary>
        public static string StarsectorTools {
            get {
                return ResourceManager.GetString("StarsectorTools", resourceCulture);
            }
        }
    }
}
