//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Windows.MainWindow {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowI18nRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowI18nRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Windows.MainWindow.MainWindowI18nRes", typeof(MainWindowI18nRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加扩展页面 的本地化字符串。
        /// </summary>
        public static string AddExtensionPage {
            get {
                return ResourceManager.GetString("AddExtensionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加页面 的本地化字符串。
        /// </summary>
        public static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动时清理游戏日志文件 的本地化字符串。
        /// </summary>
        public static string ClearGameLogOnStart {
            get {
                return ResourceManager.GetString("ClearGameLogOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件创建完毕 的本地化字符串。
        /// </summary>
        public static string ConfigFileCreationCompleted {
            get {
                return ResourceManager.GetString("ConfigFileCreationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件错误,将恢复为默认设置 的本地化字符串。
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示语言为 的本地化字符串。
        /// </summary>
        public static string DisplayLanguageIs {
            get {
                return ResourceManager.GetString("DisplayLanguageIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过长的消息 的本地化字符串。
        /// </summary>
        public static string ExcessivelyLongMessages {
            get {
                return ResourceManager.GetString("ExcessivelyLongMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展已存在 的本地化字符串。
        /// </summary>
        public static string ExtensionAlreadyExists {
            get {
                return ResourceManager.GetString("ExtensionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展文件错误 的本地化字符串。
        /// </summary>
        public static string ExtensionFileError {
            get {
                return ResourceManager.GetString("ExtensionFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展ID错误 的本地化字符串。
        /// </summary>
        public static string ExtensionIdError {
            get {
                return ResourceManager.GetString("ExtensionIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展加载错误 的本地化字符串。
        /// </summary>
        public static string ExtensionLoadError {
            get {
                return ResourceManager.GetString("ExtensionLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展目录为空 的本地化字符串。
        /// </summary>
        public static string ExtensionPathIsEmpty {
            get {
                return ResourceManager.GetString("ExtensionPathIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展信息文件未找到 的本地化字符串。
        /// </summary>
        public static string ExtensionTomlFileNotFound {
            get {
                return ResourceManager.GetString("ExtensionTomlFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一次启动软件
        ///请选择游戏启动程序 的本地化字符串。
        /// </summary>
        public static string FirstStart {
            get {
                return ResourceManager.GetString("FirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏日志清理完成 的本地化字符串。
        /// </summary>
        public static string GameLogCleanupCompleted {
            get {
                return ResourceManager.GetString("GameLogCleanupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 请重新选择 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SelectAgain {
            get {
                return ResourceManager.GetString("GameNotFound_SelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 软件即将退出 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SoftwareExit {
            get {
                return ResourceManager.GetString("GameNotFound_SoftwareExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于对游戏进行设置
        ///能修改游戏内存,清理存档和战役配装等 的本地化字符串。
        /// </summary>
        public static string GameSettingsToolTip {
            get {
                return ResourceManager.GetString("GameSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常 的本地化字符串。
        /// </summary>
        public static string GlobalException {
            get {
                return ResourceManager.GetString("GlobalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局异常 !!!警告!!!
        ///如果你看到了这个错误,说明这是意料之外的情况
        ///可能会影响软件的正常运行,建议查看日志并提交issue. 的本地化字符串。
        /// </summary>
        public static string GlobalExceptionMessage {
            get {
                return ResourceManager.GetString("GlobalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局扩展异常 的本地化字符串。
        /// </summary>
        public static string GlobalExtensionException {
            get {
                return ResourceManager.GetString("GlobalExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局扩展异常 {0} !!!警告!!!
        ///如果你看到了这个错误,说明这是扩展中意料之外的情况
        ///可能会影响扩展的正常运行,建议查看日志并提交issue至扩展开发者. 的本地化字符串。
        /// </summary>
        public static string GlobalExtensionExceptionMessage {
            get {
                return ResourceManager.GetString("GlobalExtensionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此扩展支持的软件版本与当前版本不一致,可能会出现兼容问题 的本地化字符串。
        /// </summary>
        public static string IncompatibleExtension {
            get {
                return ResourceManager.GetString("IncompatibleExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化完成 的本地化字符串。
        /// </summary>
        public static string InitializationCompleted {
            get {
                return ResourceManager.GetString("InitializationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化错误 的本地化字符串。
        /// </summary>
        public static string InitializationError {
            get {
                return ResourceManager.GetString("InitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组管理器 的本地化字符串。
        /// </summary>
        public static string ModManager {
            get {
                return ResourceManager.GetString("ModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于浏览并管理游戏模组
        ///有启用禁用,收藏,设置用户分组等功能 的本地化字符串。
        /// </summary>
        public static string ModManagerToolTip {
            get {
                return ResourceManager.GetString("ModManagerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面 的本地化字符串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未保存
        ///确定保存吗? 的本地化字符串。
        /// </summary>
        public static string PageCheckSave {
            get {
                return ResourceManager.GetString("PageCheckSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面关闭错误 的本地化字符串。
        /// </summary>
        public static string PageCloseError {
            get {
                return ResourceManager.GetString("PageCloseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面初始化错误 的本地化字符串。
        /// </summary>
        public static string PageInitializeError {
            get {
                return ResourceManager.GetString("PageInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面列表刷新完成 的本地化字符串。
        /// </summary>
        public static string PageListRefreshComplete {
            get {
                return ResourceManager.GetString("PageListRefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面不存在 的本地化字符串。
        /// </summary>
        public static string PageNotPresent {
            get {
                return ResourceManager.GetString("PageNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面保存错误 的本地化字符串。
        /// </summary>
        public static string PageSaveError {
            get {
                return ResourceManager.GetString("PageSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新扩展列表 的本地化字符串。
        /// </summary>
        public static string RefreshExtensionList {
            get {
                return ResourceManager.GetString("RefreshExtensionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新页面 的本地化字符串。
        /// </summary>
        public static string RefreshPage {
            get {
                return ResourceManager.GetString("RefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示页面 的本地化字符串。
        /// </summary>
        public static string ShowPage {
            get {
                return ResourceManager.GetString("ShowPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远行星号工具箱 的本地化字符串。
        /// </summary>
        public static string StarsectorTools {
            get {
                return ResourceManager.GetString("StarsectorTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
    }
}
