//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorToolbox.Langs.Pages.Settings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsPageI18nRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageI18nRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorToolbox.Langs.Pages.Settings.SettingsPageI18nRes", typeof(SettingsPageI18nRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除拓展调试目录 的本地化字符串。
        /// </summary>
        public static string ClearExtensionDebugPath {
            get {
                return ResourceManager.GetString("ClearExtensionDebugPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件错误 的本地化字符串。
        /// </summary>
        public static string ConfigFileError {
            get {
                return ResourceManager.GetString("ConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新载入后生效,需要重载吗? 的本地化字符串。
        /// </summary>
        public static string EffectiveAfterReload {
            get {
                return ResourceManager.GetString("EffectiveAfterReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拓展调试路径 的本地化字符串。
        /// </summary>
        public static string ExtensionDebugPath {
            get {
                return ResourceManager.GetString("ExtensionDebugPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拓展调试路径设置 的本地化字符串。
        /// </summary>
        public static string ExtensionDebugPathSetting {
            get {
                return ResourceManager.GetString("ExtensionDebugPathSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于指定拓展的路径,方便开发者调试. 的本地化字符串。
        /// </summary>
        public static string ExtensionDebugPathToolTip {
            get {
                return ResourceManager.GetString("ExtensionDebugPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言切换为 的本地化字符串。
        /// </summary>
        public static string LanguageSwitch {
            get {
                return ResourceManager.GetString("LanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志输出级别: 的本地化字符串。
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调试 的本地化字符串。
        /// </summary>
        public static string LogLevel_DEBUG {
            get {
                return ResourceManager.GetString("LogLevel_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string LogLevel_INFO {
            get {
                return ResourceManager.GetString("LogLevel_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string LogLevel_WARN {
            get {
                return ResourceManager.GetString("LogLevel_WARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志输出级别切换为 的本地化字符串。
        /// </summary>
        public static string LogLevelSwitch {
            get {
                return ResourceManager.GetString("LogLevelSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志文件 的本地化字符串。
        /// </summary>
        public static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择调试文件 的本地化字符串。
        /// </summary>
        public static string SelectDebugFile {
            get {
                return ResourceManager.GetString("SelectDebugFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置拓展调试目录 的本地化字符串。
        /// </summary>
        public static string SetExtensionDebugPath {
            get {
                return ResourceManager.GetString("SetExtensionDebugPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ST设置 的本地化字符串。
        /// </summary>
        public static string STSetting {
            get {
                return ResourceManager.GetString("STSetting", resourceCulture);
            }
        }
    }
}
