//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorToolbox.Langs.Windows.CrashReporter {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrashReporterI18nRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrashReporterI18nRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorToolbox.Langs.Windows.CrashReporter.CrashReporterI18nRes", typeof(CrashReporterI18nRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 游戏信息 的本地化字符串。
        /// </summary>
        internal static string GameInfo {
            get {
                return ResourceManager.GetString("GameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        internal static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java路径 的本地化字符串。
        /// </summary>
        internal static string JavaPath {
            get {
                return ResourceManager.GetString("JavaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java版本 的本地化字符串。
        /// </summary>
        internal static string JavaVersion {
            get {
                return ResourceManager.GetString("JavaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组Id 的本地化字符串。
        /// </summary>
        internal static string ModId {
            get {
                return ResourceManager.GetString("ModId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组已启用 的本地化字符串。
        /// </summary>
        internal static string ModIsEnabled {
            get {
                return ResourceManager.GetString("ModIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组名称 的本地化字符串。
        /// </summary>
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组信息 的本地化字符串。
        /// </summary>
        internal static string ModsInfo {
            get {
                return ResourceManager.GetString("ModsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组版本 的本地化字符串。
        /// </summary>
        internal static string ModVersion {
            get {
                return ResourceManager.GetString("ModVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作系统 的本地化字符串。
        /// </summary>
        internal static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统架构 的本地化字符串。
        /// </summary>
        internal static string PlatformArchitecture {
            get {
                return ResourceManager.GetString("PlatformArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统版本 的本地化字符串。
        /// </summary>
        internal static string PlatformVersion {
            get {
                return ResourceManager.GetString("PlatformVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统信息 的本地化字符串。
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存总量 的本地化字符串。
        /// </summary>
        internal static string TotalMemory {
            get {
                return ResourceManager.GetString("TotalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 虚拟机参数 的本地化字符串。
        /// </summary>
        internal static string VmparamsData {
            get {
                return ResourceManager.GetString("VmparamsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
