//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Libs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameInfo_I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameInfo_I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Libs.GameInfo_I18n", typeof(GameInfo_I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 遗弃船 的本地化字符串。
        /// </summary>
        public static string Derelict {
            get {
                return ResourceManager.GetString("Derelict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 霸主 的本地化字符串。
        /// </summary>
        public static string Hegemony {
            get {
                return ResourceManager.GetString("Hegemony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自由联盟 的本地化字符串。
        /// </summary>
        public static string Independent {
            get {
                return ResourceManager.GetString("Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卢德骑士团 的本地化字符串。
        /// </summary>
        public static string KnightsOfLudd {
            get {
                return ResourceManager.GetString("KnightsOfLudd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狮心守卫 的本地化字符串。
        /// </summary>
        public static string LionsGuard {
            get {
                return ResourceManager.GetString("LionsGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卢德教会 的本地化字符串。
        /// </summary>
        public static string LuddicChurch {
            get {
                return ResourceManager.GetString("LuddicChurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卢德左径 的本地化字符串。
        /// </summary>
        public static string LuddicPath {
            get {
                return ResourceManager.GetString("LuddicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雇佣兵 的本地化字符串。
        /// </summary>
        public static string Mercenary {
            get {
                return ResourceManager.GetString("Mercenary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中立 的本地化字符串。
        /// </summary>
        public static string Neutral {
            get {
                return ResourceManager.GetString("Neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欧米伽 的本地化字符串。
        /// </summary>
        public static string Omega {
            get {
                return ResourceManager.GetString("Omega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英仙座联盟 的本地化字符串。
        /// </summary>
        public static string Persean {
            get {
                return ResourceManager.GetString("Persean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海盗 的本地化字符串。
        /// </summary>
        public static string Pirates {
            get {
                return ResourceManager.GetString("Pirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 难民 的本地化字符串。
        /// </summary>
        public static string Poor {
            get {
                return ResourceManager.GetString("Poor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 余辉 的本地化字符串。
        /// </summary>
        public static string Remnant {
            get {
                return ResourceManager.GetString("Remnant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拾荒者 的本地化字符串。
        /// </summary>
        public static string Scavengers {
            get {
                return ResourceManager.GetString("Scavengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 辛达强权 的本地化字符串。
        /// </summary>
        public static string SindrianDiktat {
            get {
                return ResourceManager.GetString("SindrianDiktat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渗透者 的本地化字符串。
        /// </summary>
        public static string Sleeper {
            get {
                return ResourceManager.GetString("Sleeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速子科技 的本地化字符串。
        /// </summary>
        public static string Tritachyon {
            get {
                return ResourceManager.GetString("Tritachyon", resourceCulture);
            }
        }
    }
}
