//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorToolbox.Langs.Libs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UtilsI18nRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UtilsI18nRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorToolbox.Langs.Libs.UtilsI18nRes", typeof(UtilsI18nRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在 的本地化字符串。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过长的消息 的本地化字符串。
        /// </summary>
        public static string ExcessivelyLongMessages {
            get {
                return ResourceManager.GetString("ExcessivelyLongMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件未找到 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录错误 的本地化字符串。
        /// </summary>
        public static string GameDirectoryError {
            get {
                return ResourceManager.GetString("GameDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录为空 的本地化字符串。
        /// </summary>
        public static string GameDirectoryIsEmpty {
            get {
                return ResourceManager.GetString("GameDirectoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录设置完毕 的本地化字符串。
        /// </summary>
        public static string GameDirectorySetCompleted {
            get {
                return ResourceManager.GetString("GameDirectorySetCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本获取失败 的本地化字符串。
        /// </summary>
        public static string GameVersionAccessFailed {
            get {
                return ResourceManager.GetString("GameVersionAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本获取失败
        ///请启动一次游戏后重启工具箱 的本地化字符串。
        /// </summary>
        public static string GameVersionAccessFailedMessage {
            get {
                return ResourceManager.GetString("GameVersionAccessFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入错误 的本地化字符串。
        /// </summary>
        public static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模组信息错误 的本地化字符串。
        /// </summary>
        public static string ModInfoError {
            get {
                return ResourceManager.GetString("ModInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进程启动错误 的本地化字符串。
        /// </summary>
        public static string ProcessStartError {
            get {
                return ResourceManager.GetString("ProcessStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩文件错误 的本地化字符串。
        /// </summary>
        public static string ZipFileError {
            get {
                return ResourceManager.GetString("ZipFileError", resourceCulture);
            }
        }
    }
}
