//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Pages.GameSettings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameSettingsPageI18nRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameSettingsPageI18nRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Pages.GameSettings.GameSettingsPageI18nRes", typeof(GameSettingsPageI18nRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无边框窗口 的本地化字符串。
        /// </summary>
        public static string BorderlessWindow {
            get {
                return ResourceManager.GetString("BorderlessWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有 的本地化字符串。
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理日志文件 的本地化字符串。
        /// </summary>
        public static string ClearLogFile {
            get {
                return ResourceManager.GetString("ClearLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理装配 的本地化字符串。
        /// </summary>
        public static string ClearMissionsLoadouts {
            get {
                return ResourceManager.GetString("ClearMissionsLoadouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理存档 的本地化字符串。
        /// </summary>
        public static string ClearSave {
            get {
                return ResourceManager.GetString("ClearSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义分辨率 的本地化字符串。
        /// </summary>
        public static string CustomResolution {
            get {
                return ResourceManager.GetString("CustomResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义分辨率获取失败 的本地化字符串。
        /// </summary>
        public static string CustomResolutionGetFailed {
            get {
                return ResourceManager.GetString("CustomResolutionGetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意: 设置自定义分辨率后不能启用全屏 的本地化字符串。
        /// </summary>
        public static string CustomResolutionHelp {
            get {
                return ResourceManager.GetString("CustomResolutionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义分辨率重置错误 的本地化字符串。
        /// </summary>
        public static string CustomResolutionResetError {
            get {
                return ResourceManager.GetString("CustomResolutionResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义分辨率设置成功 的本地化字符串。
        /// </summary>
        public static string CustomResolutionSetComplete {
            get {
                return ResourceManager.GetString("CustomResolutionSetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义分辨率设置错误 的本地化字符串。
        /// </summary>
        public static string CustomResolutionSetupError {
            get {
                return ResourceManager.GetString("CustomResolutionSetupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录不存在 的本地化字符串。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件未找到 的本地化字符串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录 的本地化字符串。
        /// </summary>
        public static string GameDirectory {
            get {
                return ResourceManager.GetString("GameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏序列码 的本地化字符串。
        /// </summary>
        public static string GameKey {
            get {
                return ResourceManager.GetString("GameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏日志清理 的本地化字符串。
        /// </summary>
        public static string GameLogClean {
            get {
                return ResourceManager.GetString("GameLogClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏日志清理完成 的本地化字符串。
        /// </summary>
        public static string GameLogCleanupCompleted {
            get {
                return ResourceManager.GetString("GameLogCleanupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 请重新选择 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SelectAgain {
            get {
                return ResourceManager.GetString("GameNotFound_SelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大内存不能超过 的本地化字符串。
        /// </summary>
        public static string MaxMemoryConnotExceed {
            get {
                return ResourceManager.GetString("MaxMemoryConnotExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小内存不能低于 的本地化字符串。
        /// </summary>
        public static string MinMemoryConnotLowThan {
            get {
                return ResourceManager.GetString("MinMemoryConnotLowThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役装配清理 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsClean {
            get {
                return ResourceManager.GetString("MissionsLoadoutsClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役配装文件清理完成 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsClearCompleted {
            get {
                return ResourceManager.GetString("MissionsLoadoutsClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役配装文件不存在 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsNotExist {
            get {
                return ResourceManager.GetString("MissionsLoadoutsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开目录 的本地化字符串。
        /// </summary>
        public static string OpenDirectory {
            get {
                return ResourceManager.GetString("OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志文件 的本地化字符串。
        /// </summary>
        public static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开配装目录 的本地化字符串。
        /// </summary>
        public static string OpenMissionsLoadoutsDirectory {
            get {
                return ResourceManager.GetString("OpenMissionsLoadoutsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开存档目录 的本地化字符串。
        /// </summary>
        public static string OpenSaveDirectory {
            get {
                return ResourceManager.GetString("OpenSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        public static string ReplicationSuccess {
            get {
                return ResourceManager.GetString("ReplicationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置成功 的本地化字符串。
        /// </summary>
        public static string ResetSuccessful {
            get {
                return ResourceManager.GetString("ResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留最近存档数 的本地化字符串。
        /// </summary>
        public static string RetainRecentSaveCount {
            get {
                return ResourceManager.GetString("RetainRecentSaveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档清理 的本地化字符串。
        /// </summary>
        public static string SaveClean {
            get {
                return ResourceManager.GetString("SaveClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档清理完成 的本地化字符串。
        /// </summary>
        public static string SaveCleanComplete {
            get {
                return ResourceManager.GetString("SaveCleanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档不存在 的本地化字符串。
        /// </summary>
        public static string SaveNotExist {
            get {
                return ResourceManager.GetString("SaveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置目录 的本地化字符串。
        /// </summary>
        public static string SetDirectory {
            get {
                return ResourceManager.GetString("SetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置内存 的本地化字符串。
        /// </summary>
        public static string SetMemory {
            get {
                return ResourceManager.GetString("SetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmparams 内存设置为 的本地化字符串。
        /// </summary>
        public static string VmparamsMemorySet {
            get {
                return ResourceManager.GetString("VmparamsMemorySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmparams 内存设置设置成功 的本地化字符串。
        /// </summary>
        public static string VmparamsMemorySetComplete {
            get {
                return ResourceManager.GetString("VmparamsMemorySetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽与高不能为空 的本地化字符串。
        /// </summary>
        public static string WidthAndHeightCannotBeEmpty {
            get {
                return ResourceManager.GetString("WidthAndHeightCannotBeEmpty", resourceCulture);
            }
        }
    }
}
