//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarsectorTools.Langs.Tools.GameSettings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameSettings_I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameSettings_I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarsectorTools.Langs.Tools.GameSettings.GameSettings_I18n", typeof(GameSettings_I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理Log文件 的本地化字符串。
        /// </summary>
        public static string ClearLogFiles {
            get {
                return ResourceManager.GetString("ClearLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理战役装配 的本地化字符串。
        /// </summary>
        public static string ClearMissionsLoadouts {
            get {
                return ResourceManager.GetString("ClearMissionsLoadouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理存档 的本地化字符串。
        /// </summary>
        public static string ClearSave {
            get {
                return ResourceManager.GetString("ClearSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹不存在 的本地化字符串。
        /// </summary>
        public static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏目录 的本地化字符串。
        /// </summary>
        public static string GameDirectory {
            get {
                return ResourceManager.GetString("GameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏序列码 的本地化字符串。
        /// </summary>
        public static string GameKey {
            get {
                return ResourceManager.GetString("GameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认游戏启动程序, 请重新选择 的本地化字符串。
        /// </summary>
        public static string GameNotFound_SelectAgain {
            get {
                return ResourceManager.GetString("GameNotFound_SelectAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        public static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏版本 的本地化字符串。
        /// </summary>
        public static string GameVersion {
            get {
                return ResourceManager.GetString("GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log清理 的本地化字符串。
        /// </summary>
        public static string LogClear {
            get {
                return ResourceManager.GetString("LogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log文件清理完成 的本地化字符串。
        /// </summary>
        public static string LogFileCleanCompleted {
            get {
                return ResourceManager.GetString("LogFileCleanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log文件不存在 的本地化字符串。
        /// </summary>
        public static string LogFilesNotExist {
            get {
                return ResourceManager.GetString("LogFilesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役装配清理 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsClean {
            get {
                return ResourceManager.GetString("MissionsLoadoutsClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役配装文件清理完成 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsClearCompleted {
            get {
                return ResourceManager.GetString("MissionsLoadoutsClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战役配装文件不存在 的本地化字符串。
        /// </summary>
        public static string MissionsLoadoutsNotExist {
            get {
                return ResourceManager.GetString("MissionsLoadoutsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开目录 的本地化字符串。
        /// </summary>
        public static string OpenGameDirectory {
            get {
                return ResourceManager.GetString("OpenGameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开Log文件 的本地化字符串。
        /// </summary>
        public static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开战役配装文件夹 的本地化字符串。
        /// </summary>
        public static string OpenMissionsLoadoutsFolder {
            get {
                return ResourceManager.GetString("OpenMissionsLoadoutsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开存档文件夹 的本地化字符串。
        /// </summary>
        public static string OpenSaveFolder {
            get {
                return ResourceManager.GetString("OpenSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        public static string ReplicationSuccess {
            get {
                return ResourceManager.GetString("ReplicationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保留最近存档数 的本地化字符串。
        /// </summary>
        public static string RetainRecentSaveCount {
            get {
                return ResourceManager.GetString("RetainRecentSaveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档清理 的本地化字符串。
        /// </summary>
        public static string SaveClean {
            get {
                return ResourceManager.GetString("SaveClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档清理完成 的本地化字符串。
        /// </summary>
        public static string SaveCleanCompleted {
            get {
                return ResourceManager.GetString("SaveCleanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档不存在 的本地化字符串。
        /// </summary>
        public static string SaveNotExist {
            get {
                return ResourceManager.GetString("SaveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置目录 的本地化字符串。
        /// </summary>
        public static string SetGameDirectory {
            get {
                return ResourceManager.GetString("SetGameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置内存 的本地化字符串。
        /// </summary>
        public static string SetMemory {
            get {
                return ResourceManager.GetString("SetMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmparams 内存设置为 的本地化字符串。
        /// </summary>
        public static string VmparamsMemorySet {
            get {
                return ResourceManager.GetString("VmparamsMemorySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmparams 内存设置设置成功 的本地化字符串。
        /// </summary>
        public static string VmparamsMemorySetSuccess {
            get {
                return ResourceManager.GetString("VmparamsMemorySetSuccess", resourceCulture);
            }
        }
    }
}
